In [6]:
import numpy as np

In [7]:
b=np.random.random((3,3))

In [8]:
c=np.random.random((3,3))

In [9]:
b

array([[0.11403168, 0.48777776, 0.85835799],
       [0.16096366, 0.76822207, 0.32754305],
       [0.60494512, 0.25421365, 0.32744845]])

In [10]:
c

array([[0.61119958, 0.25754481, 0.0225493 ],
       [0.54433697, 0.41480206, 0.34744784],
       [0.84068042, 0.37081862, 0.39816328]])

In [11]:
b**2

array([[0.01300322, 0.23792714, 0.73677844],
       [0.0259093 , 0.59016515, 0.10728445],
       [0.3659586 , 0.06462458, 0.10722249]])

b+=c

In [14]:
b+=c

In [15]:
b


array([[1.94763043, 1.26041218, 0.9260059 ],
       [1.79397455, 2.01262824, 1.36988656],
       [3.12698638, 1.3666695 , 1.52193829]])

In [16]:
b+c

array([[2.55883002, 1.51795699, 0.9485552 ],
       [2.33831152, 2.4274303 , 1.7173344 ],
       [3.96766679, 1.73748812, 1.92010156]])

In [17]:
2.55883002*2.55883002

6.5476110712532

In [18]:
0.0259093*0.0259093

0.00067129182649

In [ ]:
##index


In [19]:
ls=[1,2,3,4,5,6,7,8]

In [22]:
arr=np.array(ls)


In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
arr[0]

1

In [25]:
arr[1:3]=44

In [26]:
arr

array([ 1, 44, 44,  4,  5,  6,  7,  8])

In [27]:
arr

array([ 1, 44, 44,  4,  5,  6,  7,  8])

#multidim


In [31]:
arr=np.arange(90)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [33]:
arr.reshape(9,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [38]:
#Function array

In [73]:
np.random.randint(12)

7

In [70]:
arr1=np.random.randn(12)

In [71]:
arr1

array([-1.23278458, -0.14250154,  0.10925879,  0.05651966,  0.07017511,
        1.46424777,  0.77957224, -0.0695891 ,  1.80887301,  0.5047993 ,
        0.81297581,  0.4725064 ])

In [74]:
np.sqrt(arr1)

C:\Users\VIDHYADHARAN N M\AppData\Local\Temp\ipykernel_17388\3299852782.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([       nan,        nan, 0.33054317, 0.23773863, 0.26490586,
       1.21006106, 0.88293388,        nan, 1.3449435 , 0.7104923 ,
       0.90165171, 0.68739101])

In [75]:
np.exp(arr1)

array([0.2914798 , 0.86718622, 1.11545098, 1.05814741, 1.07269601,
       4.32428914, 2.18053931, 0.93277702, 6.10356489, 1.656653  ,
       2.25460729, 1.60400945])

In [76]:
#pandas

In [5]:
import numpy as np
import pandas as pd

In [80]:
my=pd.Series([1,2,3,'hello',4,5,-34])

In [81]:
my

0        1
1        2
2        3
3    hello
4        4
5        5
6      -34
dtype: object

In [82]:
type(my)

pandas.core.series.Series

In [83]:
my_series=pd.Series([1,2,3,'hello',4,5,-34],index=['a','b','c','d','e','f','g'])

In [84]:
my_series

a        1
b        2
c        3
d    hello
e        4
f        5
g      -34
dtype: object

In [86]:
my3=pd.Series({'wash':12,'russian':123})

In [87]:
my3

wash        12
russian    123
dtype: int64

In [96]:
my3[my3>100]

russian    123
dtype: int64

In [ ]:
#DATA FRAME

In [88]:
arr=np.array([[1,2,3],[4,5,6]])

In [97]:
df=pd.DataFrame(arr,columns=['c1','c2','c3'])

In [98]:
df

c1  c2  c3
0   1   2   3
1   4   5   6

In [7]:
import pandas as pd
import numpy as np

In [10]:
a={
    "city":["sydney","rome","washington","rome","tanjore"],
    "rank":["1st","2nd","3rd","1st","3rd"],
    "score1":[22,56,78,99,26],
    "score2":[77,32,56,82,100]
}

df=pd.DataFrame(a,index=pd.Index(['a','b','c','d','e'],name='letter'),
                columns=pd.Index(['city','rank','score1','score2'],name='attributes'))

In [11]:
df

attributes        city rank  score1  score2
letter                                     
a               sydney  1st      22      77
b                 rome  2nd      56      32
c           washington  3rd      78      56
d                 rome  1st      99      82
e              tanjore  3rd      26     100

In [16]:
df.iloc[3][3]

82

In [17]:
df.loc['c','score2'] #['letter',attributes]

56

In [20]:
df.iat[2,1] 

'3rd'

In [21]:
df[1:3]

attributes        city rank  score1  score2
letter                                     
b                 rome  2nd      56      32
c           washington  3rd      78      56

In [24]:
df.sort_values(by=['city','score2'])

attributes        city rank  score1  score2
letter                                     
b                 rome  2nd      56      32
d                 rome  1st      99      82
a               sydney  1st      22      77
e              tanjore  3rd      26     100
c           washington  3rd      78      56

In [27]:
m=df
m

attributes        city rank  score1  score2
letter                                     
a               sydney  1st      22      77
b                 rome  2nd      56      32
c           washington  3rd      78      56
d                 rome  1st      99      82
e              tanjore  3rd      26     100

In [28]:
m.dropna

<bound method DataFrame.dropna of attributes        city rank  score1  score2
letter                                     
a               sydney  1st      22      77
b                 rome  2nd      56      32
c           washington  3rd      78      56
d                 rome  1st      99      82
e              tanjore  3rd      26     100>

In [34]:
m.fillna(1,inplace=True)

In [35]:
m

attributes        city rank  score1  score2
letter                                     
a               sydney  1st      22      77
b                 rome  2nd      56      32
c           washington  3rd      78      56
d                 rome  1st      99      82
e              tanjore  3rd      26     100